version: '3.8'

services:
  db:
    image: postgres:12.14-alpine
    container_name: solutions-elus_pg
    environment:
      - POSTGRES_DB=sde
      - POSTGRES_USER=sde
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    volumes:
      - sde-pgdata:/var/lib/postgresql/data
    networks:
      - sde-network
    restart: always

volumes:
  sde-pgdata:
    name: sde_pgdata

networks:
  sde-network:
    external: false
    name: sde-network

